CREATE TABLE IF NOT EXISTS team_games (
    GAME_ID TEXT PRIMARY KEY,
    SEASON TEXT NOT NULL,
    TEAM_ID INTEGER NOT NULL,
    TEAM_NAME TEXT NOT NULL,
    GAME_DATE TEXT NOT NULL,
    GAME_NUMBER INTEGER NOT NULL,
    MATCHUP TEXT NOT NULL,
    HOME_AWAY TEXT NOT NULL,
    OPPONENT TEXT NOT NULL,
    WL TEXT NOT NULL,
    PTS INTEGER NOT NULL,
    PTS_OPP INTEGER NOT NULL,
    POINT_DIFF INTEGER NOT NULL
);
